version: "3.9"

services:
  app:
    build: .
    container_name: organic-ghee-app
    ports:
      - "5656:5656"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/organic-ghee
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: organic-ghee-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: